### ISSUE TITLE
bug: incorrect links in convocatoria.md

### ISSUE THREAD

**Issue by leynier** [jcematcom/jce2021#1]
https://github.com/jcematcom/jce2021/blob/7efc0b3af8751b5161f726646c9d6c6cdc952a58/content/convocatoria.md?plain=1#L52

https://github.com/jcematcom/jce2021/blob/7efc0b3af8751b5161f726646c9d6c6cdc952a58/content/convocatoria.md?plain=1#L54

**Comment by hiancdtrsnm** [comment]
:+1: thanks solve with https://github.com/jcematcom/jce2021/commit/363e22426c6051d68a27e20af30c6ff20e7f511e
